// This file is auto-generated by the Rails Stimulus setup
import { application } from "./application"

import FlashController from "./flash_controller"
application.register("flash", FlashController)
